// Package state defines all application data types and the in-memory state
// manager. Hunt type presets live here and drive detector defaults and odds display.
package state

// eggHatchDescription is the shared template tip for egg-hatch based hunt types.
const eggHatchDescription = "Capture the egg-hatch animation frame."

// HuntTypePreset holds metadata and detector defaults for one shiny hunting method.
type HuntTypePreset struct {
	// Key is the canonical identifier stored in Pokemon.HuntType. Display
	// names live in the frontend locale files, keyed by this identifier, so
	// every UI language is covered in one place.
	Key string `json:"key"`
	// OddsNumer and OddsDenom express the generic base shiny probability as a
	// fraction. The UI shows the per-game odds from gameGroups.ts instead;
	// these are the fallback for other API consumers.
	OddsNumer int `json:"odds_numer"`
	OddsDenom int `json:"odds_denom"`
	// DefaultCooldownSec is the recommended minimum seconds between counted encounters.
	DefaultCooldownSec int `json:"default_cooldown_sec"`
	// DefaultConsecutiveHits is the recommended number of matching frames before counting.
	DefaultConsecutiveHits int `json:"default_consecutive_hits"`
	// TemplateTip is an English hint shown to the user when capturing a template.
	TemplateTip string `json:"template_tip"`
}

// HuntTypePresets is the ordered list of all supported shiny hunting methods.
// The slice order determines how they appear in the UI.
var HuntTypePresets = []HuntTypePreset{
	{
		Key:                    "encounter",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the first frame of the battle intro screen when the wild Pokémon appears.",
	},
	{
		Key:                    "soft_reset",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the frame where the static Pokémon appears after the game finishes loading.",
	},
	{
		Key:                    "masuda",
		OddsNumer:              1,
		OddsDenom:              683,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the egg-hatch sparkle frame or the moment the Pokémon sprite appears.",
	},
	{
		Key:                    "fossil",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     20,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the revival cutscene frame or the lab NPC dialogue where the Pokémon is handed over.",
	},
	{
		Key:                    "gift",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     20,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the first frame of the gift-receive animation.",
	},
	{
		Key:                    "radar",
		OddsNumer:              1,
		OddsDenom:              200,
		DefaultCooldownSec:     5,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen. Each chain encounter counts separately.",
	},
	{
		Key:                    "horde",
		OddsNumer:              5,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the horde battle first frame showing all five Pokémon sprites.",
	},
	{
		Key:                    "sos",
		OddsNumer:              1,
		OddsDenom:              683,
		DefaultCooldownSec:     6,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the frame when the new ally Pokémon appears on the field.",
	},
	{
		Key:                    "outbreak",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the Pokémon encounter screen during the outbreak.",
	},
	{
		Key:                    "sandwich",
		OddsNumer:              1,
		OddsDenom:              683,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen that appears during the sandwich shiny boost effect.",
	},
	{
		Key:                    "dynamax_adventure",
		OddsNumer:              1,
		OddsDenom:              100,
		DefaultCooldownSec:     30,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the result screen at the end of the Dynamax Adventure showing the caught Pokémon.",
	},
	{
		Key:                    "max_raid",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     30,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the raid result screen when the Pokémon is caught.",
	},
	{
		Key:                    "chain_fishing",
		OddsNumer:              1,
		OddsDenom:              100,
		DefaultCooldownSec:     6,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a hooked Pokémon appears.",
	},
	{
		Key:                    "friend_safari",
		OddsNumer:              1,
		OddsDenom:              819,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Friend Safari.",
	},
	{
		Key:                    "dexnav",
		OddsNumer:              1,
		OddsDenom:              42,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the DexNav encounter battle intro screen.",
	},
	{
		Key:                    "ultra_wormhole",
		OddsNumer:              1,
		OddsDenom:              3,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen after entering an Ultra Wormhole.",
	},
	{
		Key:                    "catch_combo",
		OddsNumer:              1,
		OddsDenom:              342,
		DefaultCooldownSec:     5,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the overworld screen showing spawning Pokémon during an active catch combo.",
	},
	{
		Key:                    "tera_raid",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     30,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the raid result screen when the Tera Raid Pokémon is caught.",
	},
	{
		Key:                    "fishing",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a Pokémon bites.",
	},
	{
		Key:                    "safari_zone",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Safari Zone.",
	},
	{
		Key:                    "breeding",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            eggHatchDescription,
	},
	{
		Key:                    "dv_method",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the battle intro screen of the target Pokémon.",
	},
	{
		Key:                    "time_capsule_exploit",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the trade animation screen.",
	},
	{
		Key:                    "odd_egg",
		OddsNumer:              1,
		OddsDenom:              7,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            eggHatchDescription,
	},
	{
		Key:                    "dv_breeding",
		OddsNumer:              1,
		OddsDenom:              64,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            eggHatchDescription,
	},
	{
		Key:                    "headbutt",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a Pokémon falls from the tree.",
	},
	{
		Key:                    "roaming_reset",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the battle intro screen of the roaming Pokémon.",
	},
	{
		Key:                    "swarm",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen during a swarm event.",
	},
	{
		Key:                    "coin_case_glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen after performing the glitch.",
	},
	{
		Key:                    "rock_smash",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen after smashing a rock.",
	},
	{
		Key:                    "game_corner",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the Pokémon receive screen at the Game Corner prize counter.",
	},
	{
		Key:                    "pomeg_glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen after performing the Pomeg Glitch.",
	},
	{
		Key:                    "run_away",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the wild Pokémon encounter.",
	},
	{
		Key:                    "battle_pyramid_glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen inside the Battle Pyramid.",
	},
	{
		Key:                    "battle_tower_glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen inside the Battle Tower.",
	},
	{
		Key:                    "cute_charm_glitch",
		OddsNumer:              1,
		OddsDenom:              5,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen with Cute Charm lead.",
	},
	{
		Key:                    "honey_tree",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a Pokémon appears at the honey tree.",
	},
	{
		Key:                    "dongle_method",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the GBA-exclusive Pokémon.",
	},
	{
		Key:                    "great_marsh",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Great Marsh.",
	},
	{
		Key:                    "lucky_power",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen while Lucky Power is active.",
	},
	{
		Key:                    "poke_pelago",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the Pokémon summary screen on Isle Abeens.",
	},
	{
		Key:                    "island_scan",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the scanned Pokémon.",
	},
	{
		Key:                    "soaring",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen while soaring in the sky.",
	},
	{
		Key:                    "battle_method",
		OddsNumer:              1,
		OddsDenom:              585,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the Brilliant Pokémon.",
	},
	{
		Key:                    "curry_hunting",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the camp screen when a Pokémon visits.",
	},
	{
		Key:                    "grand_underground",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Grand Underground.",
	},
	{
		Key:                    "massive_outbreak",
		OddsNumer:              1,
		OddsDenom:              315,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a massive mass outbreak.",
	},
	{
		Key:                    "massive_outbreak_lv10",
		OddsNumer:              1,
		OddsDenom:              293,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a massive mass outbreak with Research LV10.",
	},
	{
		Key:                    "massive_outbreak_perfect",
		OddsNumer:              1,
		OddsDenom:              256,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a massive mass outbreak with perfect research.",
	},
	{
		Key:                    "outbreak_lv10",
		OddsNumer:              1,
		OddsDenom:              152,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a mass outbreak with Research LV10.",
	},
	{
		Key:                    "outbreak_perfect",
		OddsNumer:              1,
		OddsDenom:              141,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a mass outbreak with perfect research.",
	},
	{
		Key:                    "encounter_lv10",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Research LV10 active.",
	},
	{
		Key:                    "encounter_perfect",
		OddsNumer:              1,
		OddsDenom:              1024,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with perfect research active.",
	},
	{
		Key:                    "sandwich_sp1",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV1 sandwich active.",
	},
	{
		Key:                    "sandwich_sp2",
		OddsNumer:              1,
		OddsDenom:              1365,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV2 sandwich active.",
	},
	{
		Key:                    "sandwich_sp3",
		OddsNumer:              1,
		OddsDenom:              1024,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV3 sandwich active.",
	},
	{
		Key:                    "sparkling_power_lv1",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV1 active.",
	},
	{
		Key:                    "sparkling_power_lv2",
		OddsNumer:              1,
		OddsDenom:              1365,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV2 active.",
	},
	{
		Key:                    "sparkling_power_lv3",
		OddsNumer:              1,
		OddsDenom:              1024,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV3 active.",
	},
	{
		Key:                    "picnic_breeding",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the egg-hatch animation frame from a Picnic egg.",
	},
	{
		Key:                    "colosseum_bonus_disc",
		OddsNumer:              1,
		OddsDenom:              7282,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the Jirachi's summary screen after transferring from the Colosseum Bonus Disc.",
	},
	{
		Key:                    "pokemon_channel",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the Jirachi's summary screen after transferring from Pokémon Channel.",
	},
	{
		Key:                    "shadow_snag_colosseum",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the Shadow Pokémon's summary screen after snagging it in Colosseum.",
	},
	{
		Key:                    "poke_spot_xd",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen at a Poké Spot.",
	},
	{
		Key:                    "gift_xd",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     20,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the Pokémon's summary screen after receiving the gift from Pokémon XD.",
	},
	{
		Key:                    "trade_xd",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the Pokémon's summary screen after receiving the traded Pokémon from Pokémon XD.",
	},
}

// HuntTypePresetsByKey is a lookup map from hunt type key to its preset.
// Populated at package init time from HuntTypePresets.
var HuntTypePresetsByKey = func() map[string]HuntTypePreset {
	m := make(map[string]HuntTypePreset, len(HuntTypePresets))
	for _, p := range HuntTypePresets {
		m[p.Key] = p
	}
	return m
}()
