// Package state defines all application data types and the in-memory state
// manager. Hunt type presets live here and drive detector defaults and odds display.
package state

// eggHatchDescription is the shared template tip for egg-hatch based hunt types.
const eggHatchDescription = "Capture the egg-hatch animation frame."

// HuntTypePreset holds metadata and detector defaults for one shiny hunting method.
type HuntTypePreset struct {
	// Key is the canonical identifier stored in Pokemon.HuntType.
	Key string
	// NameDE is the German display name.
	NameDE string
	// NameEN is the English display name.
	NameEN string
	// OddsNumer and OddsDenom express the base shiny probability as a fraction.
	OddsNumer int
	OddsDenom int
	// DefaultCooldownSec is the recommended minimum seconds between counted encounters.
	DefaultCooldownSec int
	// DefaultConsecutiveHits is the recommended number of matching frames before counting.
	DefaultConsecutiveHits int
	// TemplateTip is an English hint shown to the user when capturing a template.
	TemplateTip string
}

// HuntTypePresets is the ordered list of all supported shiny hunting methods.
// The slice order determines how they appear in the UI.
var HuntTypePresets = []HuntTypePreset{
	{
		Key:                    "encounter",
		NameDE:                 "Zufallsbegegnung",
		NameEN:                 "Wild Encounter",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the first frame of the battle intro screen when the wild Pokémon appears.",
	},
	{
		Key:                    "soft_reset",
		NameDE:                 "Soft Reset",
		NameEN:                 "Soft Reset",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the frame where the static Pokémon appears after the game finishes loading.",
	},
	{
		Key:                    "masuda",
		NameDE:                 "Masuda-Methode",
		NameEN:                 "Masuda Method",
		OddsNumer:              1,
		OddsDenom:              683,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the egg-hatch sparkle frame or the moment the Pokémon sprite appears.",
	},
	{
		Key:                    "fossil",
		NameDE:                 "Fossil-Revival",
		NameEN:                 "Fossil Revival",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     20,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the revival cutscene frame or the lab NPC dialogue where the Pokémon is handed over.",
	},
	{
		Key:                    "gift",
		NameDE:                 "Geschenk / Mystery Gift",
		NameEN:                 "Gift / Mystery Gift",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     20,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the first frame of the gift-receive animation.",
	},
	{
		Key:                    "radar",
		NameDE:                 "Pokéradar",
		NameEN:                 "Poké Radar",
		OddsNumer:              1,
		OddsDenom:              200,
		DefaultCooldownSec:     5,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen. Each chain encounter counts separately.",
	},
	{
		Key:                    "horde",
		NameDE:                 "Horden-Begegnung",
		NameEN:                 "Horde Encounter",
		OddsNumer:              5,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the horde battle first frame showing all five Pokémon sprites.",
	},
	{
		Key:                    "sos",
		NameDE:                 "Notruf-Kette",
		NameEN:                 "SOS Chaining",
		OddsNumer:              1,
		OddsDenom:              683,
		DefaultCooldownSec:     6,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the frame when the new ally Pokémon appears on the field.",
	},
	{
		Key:                    "outbreak",
		NameDE:                 "Massenausbruch",
		NameEN:                 "Mass Outbreak",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the Pokémon encounter screen during the outbreak.",
	},
	{
		Key:                    "sandwich",
		NameDE:                 "Sandwich-Methode",
		NameEN:                 "Sandwich Method",
		OddsNumer:              1,
		OddsDenom:              683,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen that appears during the sandwich shiny boost effect.",
	},
	{
		Key:                    "dynamax_adventure",
		NameDE:                 "Dynamax-Abenteuer",
		NameEN:                 "Dynamax Adventure",
		OddsNumer:              1,
		OddsDenom:              100,
		DefaultCooldownSec:     30,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the result screen at the end of the Dynamax Adventure showing the caught Pokémon.",
	},
	{
		Key:                    "max_raid",
		NameDE:                 "Dyna-Raid",
		NameEN:                 "Max Raid Battle",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     30,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the raid result screen when the Pokémon is caught.",
	},
	{
		Key:                    "chain_fishing",
		NameDE:                 "Ketten-Angeln",
		NameEN:                 "Chain Fishing",
		OddsNumer:              1,
		OddsDenom:              100,
		DefaultCooldownSec:     6,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a hooked Pokémon appears.",
	},
	{
		Key:                    "friend_safari",
		NameDE:                 "Freundes-Safari",
		NameEN:                 "Friend Safari",
		OddsNumer:              1,
		OddsDenom:              819,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Friend Safari.",
	},
	{
		Key:                    "dexnav",
		NameDE:                 "DexNav",
		NameEN:                 "DexNav",
		OddsNumer:              1,
		OddsDenom:              512,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the DexNav encounter battle intro screen.",
	},
	{
		Key:                    "ultra_wormhole",
		NameDE:                 "Ultrapforte",
		NameEN:                 "Ultra Wormhole",
		OddsNumer:              1,
		OddsDenom:              3,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen after entering an Ultra Wormhole.",
	},
	{
		Key:                    "catch_combo",
		NameDE:                 "Fangkombo",
		NameEN:                 "Catch Combo",
		OddsNumer:              1,
		OddsDenom:              273,
		DefaultCooldownSec:     5,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the overworld screen showing spawning Pokémon during an active catch combo.",
	},
	{
		Key:                    "tera_raid",
		NameDE:                 "Tera-Raid",
		NameEN:                 "Tera Raid Battle",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     30,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the raid result screen when the Tera Raid Pokémon is caught.",
	},
	{
		Key:                    "fishing",
		NameDE:                 "Angeln",
		NameEN:                 "Fishing",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a Pokémon bites.",
	},
	{
		Key:                    "safari_zone",
		NameDE:                 "Safari-Zone",
		NameEN:                 "Safari Zone",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Safari Zone.",
	},
	{
		Key:                    "breeding",
		NameDE:                 "Zucht",
		NameEN:                 "Breeding",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            eggHatchDescription,
	},
	{
		Key:                    "dv_method",
		NameDE:                 "DV-Methode",
		NameEN:                 "DV Method",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the battle intro screen of the target Pokémon.",
	},
	{
		Key:                    "time_capsule_exploit",
		NameDE:                 "Zeitkapsel-Exploit",
		NameEN:                 "Time Capsule Exploit",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the trade animation screen.",
	},
	{
		Key:                    "odd_egg",
		NameDE:                 "Kurioses Ei",
		NameEN:                 "Odd Egg",
		OddsNumer:              1,
		OddsDenom:              7,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            eggHatchDescription,
	},
	{
		Key:                    "dv_breeding",
		NameDE:                 "DV-Zucht",
		NameEN:                 "DV Breeding",
		OddsNumer:              1,
		OddsDenom:              64,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            eggHatchDescription,
	},
	{
		Key:                    "headbutt",
		NameDE:                 "Kopfnuss",
		NameEN:                 "Headbutt",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a Pokémon falls from the tree.",
	},
	{
		Key:                    "roaming_reset",
		NameDE:                 "Roaming-Reset",
		NameEN:                 "Roaming Reset",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the battle intro screen of the roaming Pokémon.",
	},
	{
		Key:                    "swarm",
		NameDE:                 "Schwarm-Hunt",
		NameEN:                 "Swarm Hunting",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen during a swarm event.",
	},
	{
		Key:                    "coin_case_glitch",
		NameDE:                 "Münzkoffer-Glitch",
		NameEN:                 "Coin Case Glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen after performing the glitch.",
	},
	{
		Key:                    "rock_smash",
		NameDE:                 "Zertrümmerer",
		NameEN:                 "Rock Smash",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen after smashing a rock.",
	},
	{
		Key:                    "game_corner",
		NameDE:                 "Spielhalle-Resets",
		NameEN:                 "Game Corner Resets",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the Pokémon receive screen at the Game Corner prize counter.",
	},
	{
		Key:                    "pomeg_glitch",
		NameDE:                 "Grana-Glitch",
		NameEN:                 "Pomeg Glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen after performing the Pomeg Glitch.",
	},
	{
		Key:                    "run_away",
		NameDE:                 "Flucht",
		NameEN:                 "Run Away",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the wild Pokémon encounter.",
	},
	{
		Key:                    "battle_pyramid_glitch",
		NameDE:                 "Kampfpyramide-Glitch",
		NameEN:                 "Battle Pyramid Glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen inside the Battle Pyramid.",
	},
	{
		Key:                    "battle_tower_glitch",
		NameDE:                 "Duellturm-Glitch",
		NameEN:                 "Battle Tower Glitch",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     25,
		DefaultConsecutiveHits: 3,
		TemplateTip:            "Capture the encounter screen inside the Battle Tower.",
	},
	{
		Key:                    "cute_charm_glitch",
		NameDE:                 "Charmebolzen-Glitch",
		NameEN:                 "Cute Charm Glitch",
		OddsNumer:              1,
		OddsDenom:              5,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen with Cute Charm lead.",
	},
	{
		Key:                    "honey_tree",
		NameDE:                 "Honigbaum",
		NameEN:                 "Honey Tree",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen when a Pokémon appears at the honey tree.",
	},
	{
		Key:                    "dongle_method",
		NameDE:                 "Dual-Slot-Methode",
		NameEN:                 "Dongle Method",
		OddsNumer:              1,
		OddsDenom:              8192,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the GBA-exclusive Pokémon.",
	},
	{
		Key:                    "great_marsh",
		NameDE:                 "Großmoor",
		NameEN:                 "Great Marsh",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Great Marsh.",
	},
	{
		Key:                    "lucky_power",
		NameDE:                 "Glückskraft",
		NameEN:                 "Lucky Power",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen while Lucky Power is active.",
	},
	{
		Key:                    "poke_pelago",
		NameDE:                 "Pokémon-Resort",
		NameEN:                 "Poké Pelago",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the Pokémon summary screen on Isle Abeens.",
	},
	{
		Key:                    "island_scan",
		NameDE:                 "Insel-Scanner",
		NameEN:                 "Island Scan",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the scanned Pokémon.",
	},
	{
		Key:                    "soaring",
		NameDE:                 "Überfliegen",
		NameEN:                 "Soaring",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen while soaring in the sky.",
	},
	{
		Key:                    "battle_method",
		NameDE:                 "Kampf-Methode",
		NameEN:                 "Battle Method",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen of the Brilliant Pokémon.",
	},
	{
		Key:                    "curry_hunting",
		NameDE:                 "Curry-Hunt",
		NameEN:                 "Curry Hunting",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the camp screen when a Pokémon visits.",
	},
	{
		Key:                    "grand_underground",
		NameDE:                 "Untergrundhöhlen",
		NameEN:                 "Grand Underground",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the battle intro screen in the Grand Underground.",
	},
	{
		Key:                    "massive_outbreak",
		NameDE:                 "Multipler Auflauf",
		NameEN:                 "Massive Mass Outbreak",
		OddsNumer:              1,
		OddsDenom:              315,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a massive mass outbreak.",
	},
	{
		Key:                    "massive_outbreak_lv10",
		NameDE:                 "Multipler Auflauf (Fs. 10)",
		NameEN:                 "Massive Outbreak (LV10)",
		OddsNumer:              1,
		OddsDenom:              293,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a massive mass outbreak with Research LV10.",
	},
	{
		Key:                    "massive_outbreak_perfect",
		NameDE:                 "Multipler Auflauf (Perfekt)",
		NameEN:                 "Massive Outbreak (Perfect)",
		OddsNumer:              1,
		OddsDenom:              256,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a massive mass outbreak with perfect research.",
	},
	{
		Key:                    "outbreak_lv10",
		NameDE:                 "Massiver Auflauf (Fs. 10)",
		NameEN:                 "Mass Outbreak (LV10)",
		OddsNumer:              1,
		OddsDenom:              152,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a mass outbreak with Research LV10.",
	},
	{
		Key:                    "outbreak_perfect",
		NameDE:                 "Massiver Auflauf (Perfekt)",
		NameEN:                 "Mass Outbreak (Perfect)",
		OddsNumer:              1,
		OddsDenom:              141,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen during a mass outbreak with perfect research.",
	},
	{
		Key:                    "encounter_lv10",
		NameDE:                 "Begegnung (Fs. 10)",
		NameEN:                 "Encounter (LV10)",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Research LV10 active.",
	},
	{
		Key:                    "encounter_perfect",
		NameDE:                 "Begegnung (Perfekt)",
		NameEN:                 "Encounter (Perfect)",
		OddsNumer:              1,
		OddsDenom:              1024,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with perfect research active.",
	},
	{
		Key:                    "sandwich_sp1",
		NameDE:                 "Sandwich (Schillerkraft 1)",
		NameEN:                 "Sandwich (Sparkling Power 1)",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV1 sandwich active.",
	},
	{
		Key:                    "sandwich_sp2",
		NameDE:                 "Sandwich (Schillerkraft 2)",
		NameEN:                 "Sandwich (Sparkling Power 2)",
		OddsNumer:              1,
		OddsDenom:              1365,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV2 sandwich active.",
	},
	{
		Key:                    "sandwich_sp3",
		NameDE:                 "Sandwich (Schillerkraft 3)",
		NameEN:                 "Sandwich (Sparkling Power 3)",
		OddsNumer:              1,
		OddsDenom:              1024,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV3 sandwich active.",
	},
	{
		Key:                    "sparkling_power_lv1",
		NameDE:                 "Schillerkraft St. 1",
		NameEN:                 "Sparkling Power LV1",
		OddsNumer:              1,
		OddsDenom:              2048,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV1 active.",
	},
	{
		Key:                    "sparkling_power_lv2",
		NameDE:                 "Schillerkraft St. 2",
		NameEN:                 "Sparkling Power LV2",
		OddsNumer:              1,
		OddsDenom:              1365,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV2 active.",
	},
	{
		Key:                    "sparkling_power_lv3",
		NameDE:                 "Schillerkraft St. 3",
		NameEN:                 "Sparkling Power LV3",
		OddsNumer:              1,
		OddsDenom:              1024,
		DefaultCooldownSec:     8,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the encounter screen with Sparkling Power LV3 active.",
	},
	{
		Key:                    "picnic_breeding",
		NameDE:                 "Picknick-Zucht",
		NameEN:                 "Picnic Breeding",
		OddsNumer:              1,
		OddsDenom:              4096,
		DefaultCooldownSec:     15,
		DefaultConsecutiveHits: 2,
		TemplateTip:            "Capture the egg-hatch animation frame from a Picnic egg.",
	},
}

// HuntTypePresetsByKey is a lookup map from hunt type key to its preset.
// Populated at package init time from HuntTypePresets.
var HuntTypePresetsByKey = func() map[string]HuntTypePreset {
	m := make(map[string]HuntTypePreset, len(HuntTypePresets))
	for _, p := range HuntTypePresets {
		m[p.Key] = p
	}
	return m
}()
