// Package server — swagger.go serves the Swagger UI and the OpenAPI spec.
//
// Since http-swagger/v2 depends on swaggo/swag v1, which is incompatible
// with the v2 spec registry, this file provides a lightweight handler that
// reads the generated OpenAPI document from swag/v2 and renders Swagger UI
// via the official swagger-ui CDN assets.
package server

import (
	"net/http"
	"strings"

	swag "github.com/swaggo/swag/v2"
)

// swaggerUIHTML is a minimal HTML page that loads Swagger UI from the
// official CDN and points it at the local /swagger/doc.json endpoint.
const swaggerUIHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Encounty API — Swagger UI</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    SwaggerUIBundle({
      url: "/swagger/doc.json",
      dom_id: "#swagger-ui",
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset,
      ],
      layout: "BaseLayout",
    });
  </script>
</body>
</html>`

// swaggerHandler returns an http.Handler that serves both the Swagger UI
// page and the OpenAPI JSON spec generated by swag v2.
func swaggerHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/swagger")
		path = strings.TrimPrefix(path, "/")

		switch path {
		case "doc.json":
			doc, err := swag.ReadDoc()
			if err != nil {
				http.Error(w, "failed to read OpenAPI spec", http.StatusInternalServerError)
				return
			}
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			_, _ = w.Write([]byte(doc))
		default:
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
			_, _ = w.Write([]byte(swaggerUIHTML))
		}
	})
}
